apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gist-api-go
  namespace: argocd
  annotations:
    # Image Updater still watches the container image
    argocd-image-updater.argoproj.io/image-list: my-app=192.168.56.105/gist-api-go/gist-api-go
    argocd-image-updater.argoproj.io/my-app.helm.image-spec: app.image.tag
    
    # Git Write-back Logic
    argocd-image-updater.argoproj.io/write-back-method: git:pull-request
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    # 1. Point to the HARBOR OCI Registry for the Chart
    repoURL: 192.168.56.105
    # 2. Specify the Chart name in Harbor
    chart: gist-api-go/gist-api-go
    # 3. Target a specific chart version
    targetRevision: 0.1.2
    helm:
      parameters:
        - name: app.image.name
          value: 192.168.56.105/gist-api-go/gist-api-go
        - name: app.image.tag
          value: "0.1.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: app-ns
  syncPolicy:
    automated:
      selfHeal: true